#Exemplo Aula 1

#Bibliotecas


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random as rnd

#Variável, Listas e Dataframes
- Varável

In [ ]:
a = 'sergio'
a

In [ ]:
b = 3
b

In [ ]:
c = True
c

- Como criar listas

In [ ]:
lista1 = [1, 'a', 7, False]
lista1

-Dicionário

In [ ]:
dicionario = {'lista1': lista1,
              'lista2': [30, 'hamburguer', 9, False]}

In [ ]:
dicionario

# Data Frame

In [ ]:
dados_salarios = pd.DataFrame({'nome': ['sergio', 'alice', 'cristiano ronaldo'],
 'salario': [1600, 1650, 900]})

dados_salarios

print(dados_salarios, 1+1)

                nome  salario
0             sergio     1600
1              alice     1650
2  cristiano ronaldo      900 2


#Aula 3/10
- Funcoes, logaritimos, exponenciais e vetores


In [ ]:
def funcao_potencia(n1, potencia):

  return n1**potencia

In [ ]:
funcao_potencia(4, 4)

In [ ]:
np.log (5)

In [ ]:
np.exp(7)

In [ ]:
def funcao_teste(nsoma1, nsoma2, ndiv, nmult, nteste):

  funcao = (nteste + (nsoma1 + nsoma2)) / ndiv * nmult

  return funcao



In [ ]:
funcao_teste(1,2,3,4,5)

#Listas

In [ ]:
vetor = list(range(2, 8))
vetor

[2, 3, 4, 5, 6, 7]

In [ ]:
vetor1 = list(range(4, 10))
vetor1

[4, 5, 6, 7, 8, 9]

In [ ]:
list(range(1, 20, 2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [ ]:
list(range(3, 20, 5))

[3, 8, 13, 18]

In [ ]:
list(range(2, 20, 2))

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
#lista customizada

lista2 = [1,2,10,100]
lista2

[1, 2, 10, 100]

#Listas
- valores aleatórios, loops, sequencia, impressoes sequenciais etc

In [ ]:
for i in range(7):
  print(i)

0
1
2
3
4
5
6


In [ ]:
for nome in ['di','ma']:
  print(nome)

di
ma


In [ ]:
#loop para criar uma sequencia de numeros aleatorios
#round serve para limitar o numero de casas
for i in range(5):

  print(round(rnd.uniform(0, 1), 2))

0.5
0.24
0.65
0.8
0.02


In [ ]:
#loop para criar listas de numeros aleatorios

[round(rnd.uniform(0, 10), 1 ) for i in range(10)]

[2.8, 3.5, 3.8, 3.7, 1.4, 6.5, 6.5, 5.6, 8.0, 3.6]

In [ ]:
#atribuindo a uma variável

vetor_random = [round(rnd.uniform(0, 10), 1 ) for i in range(10)]

vetor_random

In [ ]:
#loop para criar listas de numeros aleatorios inteiros
vetor_random_inteiros = rnd.sample(range(50, 400), 2)

vetor_random_inteiros

[58, 97]

In [ ]:
#somar listas numpy
np.array(vetor) + np.array(vetor1)

array([ 6,  8, 10, 12, 14, 16])

In [ ]:
#multiplicar listas numpy
np.array(vetor) * np.array(vetor1)

array([ 8, 15, 24, 35, 48, 63])

In [ ]:
#atribuindo as arrays como variaveis para simplificação

vt_np = np.array(vetor)
vt1_np = np.array(vetor1)

vt_np + vt1_np

array([ 6,  8, 10, 12, 14, 16])

In [ ]:
#criar matrizes
matriz1 = np.array([[1,3], [2,4]])

matriz1

matriz2 = np.array ([[5,6] , [7,8]])


In [ ]:
matriz2 + matriz1

array([[ 6,  9],
       [ 9, 12]])

In [ ]:
#criar matrizes com numeros aleatorios
matrizrandom = np.random.rand(2,2)

matrizrandom

array([[0.42605977, 0.47359195],
       [0.32174576, 0.816346  ]])

In [ ]:
#operações numéricas de matrizes
matriz2 - matriz1

array([[4, 3],
       [5, 4]])

In [ ]:
#multiplicação de elementos de matrizes

matriz1 * matriz2

array([[ 5, 18],
       [14, 32]])

In [ ]:
#multiplicação de matrizes
matriz1.dot(matriz2)

array([[26, 30],
       [38, 44]])

#Exercícios

In [ ]:
#ex1
def ex1(x):
    res = (x - min(x)) / (max(x) - min(x))

    return res

In [ ]:
#Exercício 2

vetorA = np.array(list(range(1, 21)))
vetorA

In [ ]:
vetorB = np.array(rnd.sample(range(1, 21), 20))
vetorB

In [ ]:
#ex3 normalizando vetor - colocando ele na funcao como se fosse o x
vetorA_norm = ex1(vetorA)
vetorB_norm = ex1(vetorB)


In [ ]:
#deixando a matriz vertical
matrizAB = np.transpose([vetorA, vetorB])
matrizAB


In [ ]:
#criando matriz e deixando vertical com os vetores normalizados
matrizAB_norm = np.transpose([vetorA_norm, vetorB_norm])

#Mmultiplicação de matrizes deixando 20,20
matrizdot = matrizAB.dot(matrizAB_norm.T)
matrizdot

In [ ]:
matrizAB_norm

In [ ]:
#multiplicação dos elementos da matrizes
matrizAB * matrizAB_norm

In [ ]:
#multiplicação de matrizes so mostrando o tamanho da matriz
matrizAB.dot(np.transpose(matrizAB_norm)).shape

(20, 20)

In [ ]:
#multiplicação de matrizes deixando 2,2
np.transpose(matrizAB).dot(matrizAB_norm)

array([[140., 100.],
       [100., 140.]])